add string and reactivate windows compilation cpu
conda-forge/kokkos-feedstock pull request #35
Opened 2024-07-13 08:52 UTC by fbordeu

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2024-07-13 08:52 UTC, fbordeu commented
@conda-forge-admin, please rerender

2024-07-14 10:35 UTC, fbordeu commented
@conda-forge-admin, please rerender

2024-07-15 15:53 UTC, fbordeu commented
Hello @BastianZim @carterbox @vincentmr ,

After a lot of trial and error. i finally made a windows kokkos compatible recipe (cpu only). it is not perfect .

Can you review this PR and tell me what to change before a merge.

Thanks 
Felipe

2024-07-15 17:33 UTC, vincentmr reviewed
Looks good, thanks a lot @fbordeu. Have you been able to test the built package in some way? Also, any chance adding `{{ stdlib("c") }}` in the dependencies?

2024-07-15 17:33 UTC, vincentmr commented on recipe/meta.yaml
> +#    - msvc.patch  # [win]
```suggestion
```

2024-07-15 17:33 UTC, vincentmr commented on recipe/meta.yaml
> +{% endif %}
Is this still required with the introduction of `cuda_present`?
```suggestion
{% if cuda_present != "None" %}
    - {{ compiler('cuda') }}
{% endif %}
```

2024-07-15 19:44 UTC, carterbox requested changes

2024-07-15 19:44 UTC, carterbox commented on recipe/meta.yaml
> +#    - msvc.patch  # [win]
Please also delete the patch file if it is no longer needed.

2024-07-15 19:44 UTC, carterbox commented on recipe/meta.yaml
> +{% endif %}
The jinja conditional `if cuda_present != "None"` is redundant because the selector `cuda_compiler_version != "None"` is already used. Please remove the `cuda_present` jinja variable. In most of the places where it was added, it is redundant.

2024-07-15 19:44 UTC, carterbox commented on recipe/meta.yaml
> +  string: "{{ kokkos_proc_type }}"
```suggestion
  # FIXME: Add a jinja variable which holds the build number 
  string: cuda{{ cuda_major }}h{{ PKG_HASH }}_{{ build }}  # [cuda_compiler_version != "None"]
  string: h{{ PKG_HASH }}_{{ build }}  # [cuda_compiler_version == "None"]
```
`kokkos_proc_type` is not unique enough to give future builds a unique build string.

2024-07-15 19:47 UTC, carterbox commented on recipe/meta.yaml
> +{% endif %}
If builds are failing locally for you because "cuda_compiler_version" is undefined, it is because you aren't including one of the build variant config files from the `.ci_support/` folder. These are the files that contain the pinnings for the packages on our channel including the compiler versions.

2024-07-16 19:23 UTC, fbordeu commented
Thank for taking mi PR seriously, I'm going to clean the recipe and ping you when ready.
Yes, I tested the compilation on my work windows (cpu kokkos) and It works correctly (for my use case). 
I'm gonna testes on a windows with gpu to see if it works.

Felipe

2024-07-16 19:24 UTC, fbordeu commented on recipe/meta.yaml
> +#    - msvc.patch  # [win]
done

2024-07-16 19:52 UTC, fbordeu commented on recipe/meta.yaml
> +  string: "{{ kokkos_proc_type }}"
perfect,

2024-07-16 20:10 UTC, fbordeu commented
@conda-forge-admin, please rerender

2024-07-17 09:04 UTC, fbordeu commented on recipe/meta.yaml
> +{% endif %}
thanks for the hints, solved.

2024-07-18 20:32 UTC, fbordeu commented
hi @BastianZim @carterbox @vincentmr ,

Almost finish, I tested the windows cpu version locally an it works for my (in my lib).

I tried to update the conda_build_config.yaml with the bot comment, but I do not know exactly how the conda-forge machinery works. An I don't have mush experience in OsX development. 

Can you help me with the last bot message ?

"""
   You are setting c_stdlib_version below the current global baseline in conda-forge (10.13). If this is your intention, you also need to override MACOSX_DEPLOYMENT_TARGET (with the same value) locally.
"""

also I ran out of ideas to make the windows cuda 11.8 variant compile. Maybe its time to ping kokkos developers??

Felipe

2024-07-18 21:20 UTC, vincentmr commented on recipe/conda_build_config.yaml
> +  - 10.13                      # [osx and arm64]
Have you tried this and rerendered? 
```suggestion
  - 11.0                      # [osx and x86_64]
  - 11.0                      # [osx and arm64]
```

2024-07-18 21:29 UTC, carterbox commented on recipe/conda_build_config.yaml
> +  - 10.13                      # [osx and arm64]
I believe we can delete this config file. I added it back before the 10.13 SDK was the channel standard. 10.13 is now the channel standard, so it is not necessary to explicitly set the SDK version (unless kokkos now requires a SDK later than 10.13).

2024-07-18 21:32 UTC, carterbox commented
@conda-forge-admin, please rerender

2024-07-18 21:35 UTC, carterbox commented
> also I ran out of ideas to make the windows cuda 11.8 variant compile. Maybe its time to ping kokkos developers??

The logs show it does compile, so what are you talking about?

2024-07-18 21:44 UTC, carterbox requested changes

2024-07-18 21:44 UTC, carterbox commented on recipe/bld.bat
> +-DKokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE=ON ^
What does this option do? Why is it necessary for Windows, but not unix?

2024-07-18 21:44 UTC, carterbox commented on recipe/meta.yaml
> +    - Kokkos_CUDA_ARGS=-DKokkos_ENABLE_CUDA=ON   # [cuda_compiler_version != "None"]
Please revert the formatting changes here.

2024-07-18 21:44 UTC, carterbox commented on recipe/meta.yaml
Please revert formatting changes here.

2024-07-18 21:44 UTC, carterbox commented on recipe/meta.yaml
> +    - cuda-driver-dev   # [not win]
Why is the driver package not needed on Windows?

2024-07-18 21:44 UTC, carterbox commented on recipe/meta.yaml
> +    - if not exist %LIBRARY_LIB%\\kokkoscore.lib exit 1  # [win]
```suggestion
    - if not exist %LIBRARY_LIB%\\kokkoscontainers.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\kokkoscore.lib exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\kokkossimd.lib exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\kokkoscontainers.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\kokkoscore.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\kokkossimd.dll exit 1  # [win]
```
Add something like this.

2024-07-18 21:44 UTC, carterbox commented on recipe/meta.yaml
> +#    - example --help  # [cuda_compiler_version == "None" and win]
It would be great if this compile test also worked for Windows.

2024-07-18 21:48 UTC, carterbox commented
@conda-forge-admin, please rerender

2024-07-19 07:44 UTC, fbordeu commented
> > also I ran out of ideas to make the windows cuda 11.8 variant compile. Maybe its time to ping kokkos developers??
> 
> The logs show it does compile, so what are you talking about?

the build is stuck and does not finish, I dont have access to the log to check what's wrong with it. 

![image](https://github.com/user-attachments/assets/9e87cd71-fe1d-41df-91c5-7c2d66d61c0b)

2024-07-19 07:49 UTC, fbordeu commented on recipe/bld.bat
> +-DKokkos_ENABLE_COMPILE_AS_CMAKE_LANGUAGE=ON ^
I'm not really sure.
I based my cmake call using the github action of kokkos:

https://github.com/kokkos/kokkos/blob/3290a3de196b6389e828b8d4f25011675737decb/CMakeLists.txt#L83

https://github.com/kokkos/kokkos/blob/develop/.github/workflows/windows.yml

2024-07-19 07:54 UTC, fbordeu commented on recipe/meta.yaml
> +    - Kokkos_CUDA_ARGS=-DKokkos_ENABLE_CUDA=ON   # [cuda_compiler_version != "None"]
sorry but I don't understand your request. the linter does not complain.

2024-07-19 07:55 UTC, fbordeu commented on recipe/meta.yaml
Sorry but I don't understand your request. the linter does not complain. Maybe the empty line?? 
I'm going to clean the empty lines.

2024-07-19 07:56 UTC, fbordeu commented on recipe/meta.yaml
> +    - cuda-driver-dev   # [not win]
cuda-driver-dev is not available on windows so I remove the line. 

https://anaconda.org/conda-forge/cuda-driver-dev

2024-07-19 09:37 UTC, fbordeu commented on recipe/meta.yaml
> +    - if not exist %LIBRARY_LIB%\\kokkoscore.lib exit 1  # [win]
done

2024-07-19 09:37 UTC, fbordeu commented on recipe/meta.yaml
> +#    - example --help  # [cuda_compiler_version == "None" and win]
just reactivated the tests cpu OK. Waiting if tests GPU ok...

2024-07-19 11:10 UTC, fbordeu commented
@conda-forge-admin, please rerender

2024-07-19 12:00 UTC, vincentmr approved these changes
Looks good to me, thanks a bunch @fbordeu . Kudos to @carterbox for all the help.

2024-07-19 12:00 UTC, vincentmr commented on recipe/meta.yaml
> +  #windows
```suggestion
  # windows
```

2024-07-19 17:11 UTC, carterbox requested changes
There are some remaining extra edits to the meta.yaml that should be reverted.

2024-07-19 17:16 UTC, carterbox commented
There's at least one hardcoded path in the Windows CMake config:

```
SET(Kokkos_CXX_COMPILER "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe")
```

Not sure if that will cause issues building downstream packages.

2024-07-19 21:24 UTC, fbordeu commented on recipe/meta.yaml
> +    - https://github.com/kokkos/kokkos/archive/refs/tags/{{ version }}.tar.gz
ups, sorry.

2024-07-19 21:29 UTC, fbordeu commented
> There's at least one hardcoded path in the Windows CMake config:
> 
> ```
> SET(Kokkos_CXX_COMPILER "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe")
> ```
> 
> Not sure if that will cause issues building downstream packages. We do a lot of patching of the unix configs to remove hardcoded paths. Probably these paths can be fixed in an future PR. Unless someone wants to test it.

I just discover all the patching for the unix version. For my compilation on windows it does not bother. I agree we can treat this is a future PR.

2024-07-22 00:32 UTC, carterbox commented
@conda-forge-admin, please rerender

2024-07-22 01:07 UTC, merged